Numpy 矩阵求逆
---

In [3]:
import numpy as np

A = np.array([[1, 0, 0, 1],
              [1, 1, 0, 1],
              [0, 1, 1, 1],
              [0, 0, 1, 0]])
A_T = np.linalg.inv(A)  # 求逆
print(A_T)

[[ 0.  1. -1.  1.]
 [-1.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1. -1.  1. -1.]]


检验合同变换
---

In [4]:
import numpy as np

A = np.array([[0,  1,  1],
              [1,  0, -3],
              [1, -3, 0]])

C = np.array([[1, -0.5, 3],
              [1, 0.5, -1],
              [0,  0,   1]])

V = (C.T).dot(A).dot(C)
print(V)

[[ 2.   0.   0. ]
 [ 0.  -0.5  0. ]
 [ 0.   0.   6. ]]


系数矩阵化为行阶梯最简形
---

In [3]:
from sympy import Matrix

A = Matrix([[1,  0,  2,  1], 
            [-1, 2,  1,  3], 
            [1,  2,  5,  5],
            [2, -2,  1, -2]])

print(A.rref())

(Matrix([
[1, 0,   2, 1],
[0, 1, 3/2, 2],
[0, 0,   0, 0],
[0, 0,   0, 0]]), (0, 1))


random.shuffle用法
---

In [4]:
import random
i =list(range(10)) 
#print(list(range(10)))
#print(range(10))

random.shuffle(i)
print(i)

[1, 6, 5, 3, 4, 2, 9, 0, 8, 7]


the End
---